"""Constants for the Midnite Solar integration."""

DOMAIN = "midnite_solar"

DEFAULT_PORT = 502
CONF_SCAN_INTERVAL = "scan_interval"
DEFAULT_SCAN_INTERVAL = 15
CONF_ENABLE_ADVANCED = "enable_advanced"
CONF_ENABLE_DEBUG = "enable_debug"
CONF_ENABLE_WRITES = "enable_writes"

# Register categories for entity creation
# B = Basic (always enabled), A = Advanced (opt-in), D = Debug (opt-in)
REGISTER_CATEGORIES = {
    "ABSORB_SETPOINT_VOLTAGE": "B",
    "ABSORB_TIME": "B",
    "ABSORB_TIME_DUPLICATE": "A",
    "ABSORB_TIME_EEPROM": "B",
    "AMP_HOURS_DAILY": "B",
    "ARC_FAULT_SENSITIVITY": "A",
    "AUX1_DELAY_T_MS": "A",
    "AUX1_HOLD_T_MS": "A",
    "AUX1_VOLTS_HI_ABS": "A",
    "AUX1_VOLTS_HI_PV_ABS": "A",
    "AUX1_VOLTS_HI_REL": "A",
    "AUX1_VOLTS_LO_ABS": "A",
    "AUX1_VOLTS_LO_PV_ABS": "A",
    "AUX1_VOLTS_LO_REL": "A",
    "AUX2_A2D_D2A": "A",
    "AUX2_PWM_VWIDTH": "A",
    "AUX2_VOLTS_HI_ABS": "A",
    "AUX2_VOLTS_HI_PV_ABS": "A",
    "AUX2_VOLTS_HI_REL": "A",
    "AUX2_VOLTS_LO_REL": "A",
    "AUX_1_AND_2_FUNCTION": "A",
    "BATTERY_OUTPUT_CURRENT_LIMIT": "B",
    "BATTERY_TEMP_COMP_VALUE": "A",
    "BATTERY_TEMP_PASSED_EEPROM": "B",
    "BATT_TEMPERATURE": "B",
    "CLASSIC_FME_PASSED_BITS_EEPROM": "A",
    "CLASSIC_MODBUS_ADDR_EEPROM": "A",
    "CLEAR_LOGS_CAT": "A",
    "CLEAR_LOGS_COUNTER_10MS": "A",
    "CLIPPER_CMD_VOLTS": "A",
    "COMBO_CHARGE_STAGE": "B",
    "CTI_ME0": "A",
    "CTI_ME0_HIGH": "A",
    "CTI_ME1": "A",
    "CTI_ME1_HIGH": "A",
    "CTI_ME2": "A",
    "DABT_U32_DEBUG_01": "D",
    "DABT_U32_DEBUG_02": "D",
    "DABT_U32_DEBUG_03": "D",
    "DABT_U32_DEBUG_04": "D",
    "DAYS_BTW_BULK_ABS_EEPROM": "A",
    "DAY_LOG_COMB_CAT_INDEX": "A",
    "DEVICE_ID_LSW": "B",
    "DEVICE_ID_MSW": "B",
    "DISP_AVG_VBATT": "B",
    "DISP_AVG_VPV": "B",
    "DNS_1_LSB_1": "A",
    "DNS_1_LSB_2": "A",
    "DNS_2_LSB_1": "A",
    "DNS_2_LSB_2": "A",
    "ENABLE_FLAGS2": "A",
    "ENABLE_FLAGS3": "A",
    "ENABLE_FLAGS_BITS": "A",
    "ENDING_AMPES_EEPROM": "A",
    "ENDING_AMPS_TIMER_SEC": "A",
    "ENDING_SOC_EEPROM": "A",
    "EQUALIZE_INTERVAL_DAYS_EEPROM": "B",
    "EQUALIZE_RETRY_DAYS": "A",
    "EQUALIZE_TIME": "B",
    "EQUALIZE_TIME_EEPROM": "B",
    "EQUALIZE_VOLTAGE_SETPOINT": "B",
    "FACTORY_VBATT_OFFSET_EEPA": "D",
    "FET_TEMPERATURE": "B",
    "FLAGS_RD_32BIT": "A",
    "FLOAT_TIME_TODAY_SEC": "B",
    "FLOAT_VOLTAGE_SETPOINT": "B",
    "FOLLOW_ME_PASS_REF_EEPROM": "A",
    "FORCE_FLAG_BITS": "A",
    "GATEWAY_ADDRESS_LSB_1": "A",
    "GATEWAY_ADDRESS_LSB_2": "A",
    "GENERAL_PURPOSE_WORD": "D",
    "H2O_SWEEP_AMPS_10TIME6_EEPA": "A",
    "HIGHEST_VINPUT_LOG": "B",
    "IBATT_DISPLAY_S": "B",
    "IBATT_RAW_A": "A",
    "INFO_FLAGS_BITS2_0": "A",
    "INFO_FLAGS_BITS2_1": "A",
    "INFO_FLAGS_BITS3": "B",
    "INPUT_VPV_RAW": "A",
    "IPV_MINUS_RAW": "A",
    "IP_ADDRESS_LSB_1": "A",
    "IP_ADDRESS_LSB_2": "A",
    "IP_SETTINGS_FLAGS": "A",
    "I_FLAGS_RO_HIGH": "A",
    "JrAmpHourNET": "A",
    "KW_HOURS": "B",
    "LED_MODE_EEPROM": "A",
    "LIFETIME_AMP_HOURS_1": "B",
    "LIFETIME_AMP_HOURS_1_HIGH": "B",
    "LIFETIME_KW_HOURS_1": "B",
    "LIFETIME_KW_HOURS_1_HIGH": "B",
    "LOW_WATTS_EEPA": "A",
    "MAC_ADDRESS_PART_1": "B",
    "MAC_ADDRESS_PART_2": "B",
    "MAC_ADDRESS_PART_3": "B",
    "MATCH_POINT_SHADOW": "A",
    "MAX_BATTERY_TEMP_COMP_VOLTAGE": "A",
    "MAX_INPUT_CURRENT_EEPROM": "A",
    "MINUTE_LOG_INTERVAL_SEC": "A",
    "MIN_ABSORB_TIME": "A",
    "MIN_BATTERY_TEMP_COMP_VOLTAGE": "A",
    "MIN_LOG_COMB_CAT_INDEX": "A",
    "MIN_SWP_VOLTAGE_EEPROM": "A",
    "MIN_VPV_TURN_ON": "A",
    "MNGP_REVISION": "B",
    "MNLP_REVISION": "B",
    "MODBUS_CONTROL_EEPROM": "A",
    "MODBUS_PORT_REGISTER": "A",
    "MPPT_MODE": "A",
    "MPP_PERCENT_VOC_EEPROM": "A",
    "MPP_W_LAST": "A",
    "NEGATIVE_CURRENT_ADJ": "A",
    "NITE_MINUTES_NO_PWR": "B",
    "NO_DOUBLE_CLICK_TIMER": "D",
    "OUTPUT_VBATT_RAW": "A",
    "PCB_TEMPERATURE": "B",
    "PK_AMPS_OVER_LIMIT_HI_EEPA": "D",
    "PK_AMPS_OVER_LIMIT_LO_EEPA": "D",
    "PK_AMPS_OVER_TRIP_EEPROM": "A",
    "PK_HOLD_VPV_STAMP": "A",
    "PREVOC": "A",
    "PV_INPUT_CURRENT": "B",
    "PWM_READONLY": "A",
    "REASON_FOR_RESET": "B",
    "REASON_FOR_RESTING": "B",
    "REBUCK_TIMER_SEC_EEPROM": "A",
    "REBUCK_VOLTS_EEPROM": "A",
    "REMOTE_BUTTONS": "A",
    "REMOTE_MENU_MODE": "A",
    "RESERVED_4105": "D",
    "RESTART_TIME_MS": "B",
    "RESTART_TIME_MS2": "A",
    "SIESTA_ABORT_VOC_ADJ": "A",
    "SIESTA_TIME_SEC": "A",
    "SLIDING_CURRENT_LIMIT": "A",
    "STATUSROLL": "B",
    "SUBNET_MASK_LSB_1": "A",
    "SUBNET_MASK_LSB_2": "A",
    "SWEEP_DEPTH": "A",
    "SWEEP_INTERVAL_SECS_EEPROM": "A",
    "SWP_DEEP_TIMEOUT_SEC": "A",
    "UNIT_ID": "B",
    "UNIT_NAME_0": "B",
    "UNIT_NAME_1": "B",
    "UNIT_NAME_2": "B",
    "UNIT_NAME_3": "B",
    "UNIT_SW_DATE_MONTH_DAY": "B",
    "UNIT_SW_DATE_RO": "B",
    "USB_COMM_MODE": "A",
    "USER_VARIABLE_02": "A",
    "VARIMAX": "A",
    "VBATT_NOMINAL_EEPROM": "A",
    "VBATT_OFFSET": "A",
    "VBATT_REG_SET_P_TEMP_COMP": "A",
    "VOC_LAST_MEASURED": "B",
    "VOC_QUALIFY_TIMER_MS_EEPROM": "A",
    "VOC_QUALIFY_TIMER_MS_EEPROM_LOW": "A",
    "VOC_RD": "A",
    "VPV_B4_TURN_OFF": "A",
    "VPV_OFFSET": "A",
    "VPV_TARGET_RD": "A",
    "VPV_TARGET_RD_TMP": "A",
    "VPV_TARGET_WR": "A",
    "WATTS": "B",
    "WINDOW_WATTS_RO_DELTA_EEPA": "A",
    "WIND_LOW_WATTS_EEPA": "A",
    "WIND_NUMBER_OF_POLES_EEPROM": "A",
    "WIND_POWER_TABLE_I_0_EEPA": "D",
    "WIND_POWER_TABLE_I_1_EEPA": "D",
    "WIND_POWER_TABLE_I_2_EEPA": "D",
    "WIND_POWER_TABLE_I_3_EEPA": "D",
    "WIND_POWER_TABLE_I_4_EEPA": "D",
    "WIND_POWER_TABLE_I_5_EEPA": "D",
    "WIND_POWER_TABLE_I_6_EEPA": "D",
    "WIND_POWER_TABLE_I_7_EEPA": "D",
    "WIND_POWER_TABLE_V_0_EEPA": "D",
    "WIND_POWER_TABLE_V_1_EEPA": "D",
    "WIND_POWER_TABLE_V_2_EEPA": "D",
    "WIND_POWER_TABLE_V_3_EEPA": "D",
    "WIND_POWER_TABLE_V_4_EEPA": "D",
    "WIND_POWER_TABLE_V_5_EEPA": "D",
    "WIND_POWER_TABLE_V_6_EEPA": "D",
    "WIND_POWER_TABLE_V_7_EEPA": "D",
    "WIND_SYNCH_A_EEPROM": "D",
    "WIND_SYNCH_V_EEPROM": "D",
    "WIND_TABLE_TO_USE_EEPROM": "A",
    "WIND_TIMEOUT2_REF_EEPA": "A",
    "WIND_TIMEOUT2_SECONDS": "A",
    "WIND_TIMEOUT_REF_EEPA": "A",
    "WIND_TIMEOUT_SECONDS": "A",
    "WIND_WINDOW_WATTS_REF_EEPA": "A",
    "WIZBANG_RX_BUFFER_TEMP_SH1": "D",
    "WIZBANG_RX_BUFFER_TEMP_SH2": "D",
    "WIZBANG_RX_BUFFER_TEMP_SH3": "D",
    "WIZBANG_RX_BUFFER_TEMP_SH4": "D",
    "WJRB_AMP_HOUR_NEGATIVE": "D",
    "WJRB_AMP_HOUR_NEGATIVE_HIGH": "D",
    "WJRB_AMP_HOUR_NET": "A",
    "WJRB_AMP_HOUR_NET_HIGH": "A",
    "WJRB_AMP_HOUR_POSITIVE": "D",
    "WJRB_AMP_HOUR_POSITIVE_HIGH": "D",
    "WJRB_CMD_S_EEPROM": "D",
    "WJRB_CURRENT_32_SIGNED_EEPROM": "A",
    "WJRB_NUMERATOR_SS_EEPROM": "D",
    "WJRB_RAW_CRC_AND_TEMP": "A",
    "WJRB_RAW_CURRENT": "D",
}

# Register addresses from REGISTER_CATEGORIES.csv (sorted by address for easy reference)
REGISTER_MAP = {
    "UNIT_ID": 4101,
    "UNIT_SW_DATE_RO": 4102,
    "UNIT_SW_DATE_MONTH_DAY": 4103,
    "INFO_FLAGS_BITS3": 4104,
    "RESERVED_4105": 4105,
    "MAC_ADDRESS_PART_1": 4106,
    "MAC_ADDRESS_PART_2": 4107,
    "MAC_ADDRESS_PART_3": 4108,
    "JrAmpHourNET": 4109,
    "DEVICE_ID_LSW": 4111,
    "DEVICE_ID_MSW": 4112,
    "STATUSROLL": 4113,
    "RESTART_TIME_MS": 4114,
    "DISP_AVG_VBATT": 4115,
    "DISP_AVG_VPV": 4116,
    "IBATT_DISPLAY_S": 4117,
    "KW_HOURS": 4118,
    "WATTS": 4119,
    "COMBO_CHARGE_STAGE": 4120,
    "PV_INPUT_CURRENT": 4121,
    "VOC_LAST_MEASURED": 4122,
    "HIGHEST_VINPUT_LOG": 4123,
    "MATCH_POINT_SHADOW": 4124,
    "AMP_HOURS_DAILY": 4125,
    "LIFETIME_KW_HOURS_1": 4126,
    "LIFETIME_KW_HOURS_1_HIGH": 4127,
    "LIFETIME_AMP_HOURS_1": 4128,
    "LIFETIME_AMP_HOURS_1_HIGH": 4129,
    "INFO_FLAGS_BITS2_1": 4130,
    "INFO_FLAGS_BITS2_0": 4131,
    "BATT_TEMPERATURE": 4132,
    "FET_TEMPERATURE": 4133,
    "PCB_TEMPERATURE": 4134,
    "NITE_MINUTES_NO_PWR": 4135,
    "MINUTE_LOG_INTERVAL_SEC": 4136,
    "MODBUS_PORT_REGISTER": 4137,
    "FLOAT_TIME_TODAY_SEC": 4138,
    "ABSORB_TIME": 4139,
    "PWM_READONLY": 4141,
    "REASON_FOR_RESET": 4142,
    "EQUALIZE_TIME": 4143,
    "MPP_W_LAST": 4145,
    "USB_COMM_MODE": 4146,
    "NO_DOUBLE_CLICK_TIMER": 4147,
    "BATTERY_OUTPUT_CURRENT_LIMIT": 4148,
    "ABSORB_SETPOINT_VOLTAGE": 4149,
    "FLOAT_VOLTAGE_SETPOINT": 4150,
    "EQUALIZE_VOLTAGE_SETPOINT": 4151,
    "SLIDING_CURRENT_LIMIT": 4152,
    "MIN_ABSORB_TIME": 4153,
    "ABSORB_TIME_EEPROM": 4154,
    "MAX_BATTERY_TEMP_COMP_VOLTAGE": 4155,
    "MIN_BATTERY_TEMP_COMP_VOLTAGE": 4156,
    "BATTERY_TEMP_COMP_VALUE": 4157,
    "GENERAL_PURPOSE_WORD": 4158,
    "EQUALIZE_RETRY_DAYS": 4159,
    "FORCE_FLAG_BITS": 4160,
    "EQUALIZE_TIME_EEPROM": 4162,
    "EQUALIZE_INTERVAL_DAYS_EEPROM": 4163,
    "MPPT_MODE": 4164,
    "AUX_1_AND_2_FUNCTION": 4165,
    "AUX1_VOLTS_LO_ABS": 4166,
    "AUX1_DELAY_T_MS": 4167,
    "AUX1_HOLD_T_MS": 4168,
    "AUX2_PWM_VWIDTH": 4169,
    "AUX1_VOLTS_HI_ABS": 4172,
    "AUX2_VOLTS_HI_ABS": 4173,
    "AUX1_VOLTS_LO_REL": 4174,
    "AUX1_VOLTS_HI_REL": 4175,
    "AUX2_VOLTS_LO_REL": 4176,
    "AUX2_VOLTS_HI_REL": 4177,
    "AUX1_VOLTS_LO_PV_ABS": 4178,
    "AUX1_VOLTS_HI_PV_ABS": 4179,
    "VARIMAX": 4180,
    "AUX2_VOLTS_HI_PV_ABS": 4181,
    "ENABLE_FLAGS3": 4182,
    "ARC_FAULT_SENSITIVITY": 4183,
    "ENABLE_FLAGS2": 4186,
    "ENABLE_FLAGS_BITS": 4187,
    "VBATT_OFFSET": 4189,
    "VPV_OFFSET": 4190,
    "VPV_TARGET_RD": 4191,
    "VPV_TARGET_WR": 4192,
    "SWEEP_INTERVAL_SECS_EEPROM": 4197,
    "MIN_SWP_VOLTAGE_EEPROM": 4198,
    "MAX_INPUT_CURRENT_EEPROM": 4199,
    "SWEEP_DEPTH": 4200,
    "NEGATIVE_CURRENT_ADJ": 4201,
    "CLIPPER_CMD_VOLTS": 4202,
    "WIND_NUMBER_OF_POLES_EEPROM": 4203,
    "MPP_PERCENT_VOC_EEPROM": 4204,
    "WIND_TABLE_TO_USE_EEPROM": 4205,
    "LED_MODE_EEPROM": 4207,
    "UNIT_NAME_0": 4210,
    "UNIT_NAME_1": 4211,
    "UNIT_NAME_2": 4212,
    "UNIT_NAME_3": 4213,
    "CTI_ME0": 4214,
    "CTI_ME0_HIGH": 4215,
    "CTI_ME1": 4216,
    "CTI_ME1_HIGH": 4217,
    "CTI_ME2": 4218,
    "REMOTE_MENU_MODE": 4220,
    "REMOTE_BUTTONS": 4221,
    "PREVOC": 4224,
    "AUX2_A2D_D2A": 4226,
    "VOC_RD": 4231,
    "ABSORB_TIME_DUPLICATE": 4236,
    "SIESTA_TIME_SEC": 4238,
    "SIESTA_ABORT_VOC_ADJ": 4239,
    "FLAGS_RD_32BIT": 4241,
    "VBATT_REG_SET_P_TEMP_COMP": 4244,
    "VBATT_NOMINAL_EEPROM": 4245,
    "ENDING_AMPES_EEPROM": 4246,
    "ENDING_SOC_EEPROM": 4247,
    "REBUCK_VOLTS_EEPROM": 4249,
    "DAYS_BTW_BULK_ABS_EEPROM": 4252,
    "DAY_LOG_COMB_CAT_INDEX": 4254,
    "MIN_LOG_COMB_CAT_INDEX": 4256,
    "REBUCK_TIMER_SEC_EEPROM": 4257,
    "VOC_QUALIFY_TIMER_MS_EEPROM_LOW": 4264,
    "VOC_QUALIFY_TIMER_MS_EEPROM": 4265,
    "IPV_MINUS_RAW": 4266,
    "RESTART_TIME_MS2": 4271,
    "IBATT_RAW_A": 4272,
    "REASON_FOR_RESTING": 4275,
    "OUTPUT_VBATT_RAW": 4276,
    "INPUT_VPV_RAW": 4277,
    "PK_HOLD_VPV_STAMP": 4280,
    "VPV_TARGET_RD_TMP": 4283,
    "SWP_DEEP_TIMEOUT_SEC": 4284,
    "LOW_WATTS_EEPA": 4286,
    "WIND_LOW_WATTS_EEPA": 4287,
    "WIND_WINDOW_WATTS_REF_EEPA": 4288,
    "WINDOW_WATTS_RO_DELTA_EEPA": 4289,
    "WIND_TIMEOUT_REF_EEPA": 4290,
    "WIND_TIMEOUT2_REF_EEPA": 4291,
    "WIND_TIMEOUT_SECONDS": 4292,
    "WIND_TIMEOUT2_SECONDS": 4293,
    "MIN_VPV_TURN_ON": 4294,
    "VPV_B4_TURN_OFF": 4295,
    "H2O_SWEEP_AMPS_10TIME6_EEPA": 4296,
    "ENDING_AMPS_TIMER_SEC": 4297,
    "PK_AMPS_OVER_LIMIT_HI_EEPA": 4298,
    "PK_AMPS_OVER_LIMIT_LO_EEPA": 4299,
    "FACTORY_VBATT_OFFSET_EEPA": 4300,
    "WIND_POWER_TABLE_V_0_EEPA": 4301,
    "WIND_POWER_TABLE_V_1_EEPA": 4302,
    "WIND_POWER_TABLE_V_2_EEPA": 4303,
    "WIND_POWER_TABLE_V_3_EEPA": 4304,
    "WIND_POWER_TABLE_V_4_EEPA": 4305,
    "WIND_POWER_TABLE_V_5_EEPA": 4306,
    "WIND_POWER_TABLE_V_6_EEPA": 4307,
    "WIND_POWER_TABLE_V_7_EEPA": 4308,
    "WIND_POWER_TABLE_I_0_EEPA": 4309,
    "WIND_POWER_TABLE_I_1_EEPA": 4310,
    "WIND_POWER_TABLE_I_2_EEPA": 4311,
    "WIND_POWER_TABLE_I_3_EEPA": 4312,
    "WIND_POWER_TABLE_I_4_EEPA": 4313,
    "WIND_POWER_TABLE_I_5_EEPA": 4314,
    "WIND_POWER_TABLE_I_6_EEPA": 4315,
    "WIND_POWER_TABLE_I_7_EEPA": 4316,
    "PK_AMPS_OVER_TRIP_EEPROM": 4318,
    "MNGP_REVISION": 4319,
    "MNLP_REVISION": 4320,
    "CLASSIC_MODBUS_ADDR_EEPROM": 4326,
    "BATTERY_TEMP_PASSED_EEPROM": 4327,
    "I_FLAGS_RO_HIGH": 4330,
    "MODBUS_CONTROL_EEPROM": 4331,
    "CLASSIC_FME_PASSED_BITS_EEPROM": 4332,
    "WIND_SYNCH_A_EEPROM": 4333,
    "WIND_SYNCH_V_EEPROM": 4334,
    "FOLLOW_ME_PASS_REF_EEPROM": 4335,
    "DABT_U32_DEBUG_01": 4341,
    "DABT_U32_DEBUG_02": 4342,
    "DABT_U32_DEBUG_03": 4343,
    "DABT_U32_DEBUG_04": 4344,
    "CLEAR_LOGS_CAT": 4354,
    "CLEAR_LOGS_COUNTER_10MS": 4355,
    "USER_VARIABLE_02": 4356,
    "WIZBANG_RX_BUFFER_TEMP_SH1": 4357,
    "WIZBANG_RX_BUFFER_TEMP_SH2": 4358,
    "WIZBANG_RX_BUFFER_TEMP_SH3": 4359,
    "WIZBANG_RX_BUFFER_TEMP_SH4": 4360,
    "WJRB_CMD_S_EEPROM": 4361,
    "WJRB_RAW_CURRENT": 4362,
    "WJRB_NUMERATOR_SS_EEPROM": 4363,
    "WJRB_AMP_HOUR_POSITIVE": 4365,
    "WJRB_AMP_HOUR_POSITIVE_HIGH": 4366,
    "WJRB_AMP_HOUR_NEGATIVE": 4367,
    "WJRB_AMP_HOUR_NEGATIVE_HIGH": 4368,
    "WJRB_AMP_HOUR_NET": 4369,
    "WJRB_AMP_HOUR_NET_HIGH": 4370,
    "WJRB_CURRENT_32_SIGNED_EEPROM": 4371,
    "WJRB_RAW_CRC_AND_TEMP": 4372,
    "IP_SETTINGS_FLAGS": 20481,
    "IP_ADDRESS_LSB_1": 20482,
    "IP_ADDRESS_LSB_2": 20483,
    "GATEWAY_ADDRESS_LSB_1": 20484,
    "GATEWAY_ADDRESS_LSB_2": 20485,
    "SUBNET_MASK_LSB_1": 20486,
    "SUBNET_MASK_LSB_2": 20487,
    "DNS_1_LSB_1": 20488,
    "DNS_1_LSB_2": 20489,
    "DNS_2_LSB_1": 20490,
    "DNS_2_LSB_2": 20491,
}

# Register groups for efficient reading and organization
REGISTER_GROUPS = {
    "device_info": [
        4101,
        4111,
        4112,
        4210,
        4211,
        4212,
        4213,
        4106,
        4107,
        4108,
        4102,
        4103,
    ],
    "status": [
        4115,
        4116,
        4117,
        4119,
        4120,
        4121,
        4122,
        4118,
        4113,
        4104,
        4142,
        4145,
        4147,
        4152,
        4153,
        4158,
        4159,
        4160,
        4272,
        4276,
        4277,
        4224,
        4280,
        4266,
        4319,
        4320,
    ],
    "temperatures": [
        4132,
        4133,
        4134,
    ],
    "energy": [
        4125,
        4126,
        4127,
        4128,
        4129,
    ],
    "time_settings": [
        4138,
        4139,
        4143,
        4114,
    ],
    "diagnostics": [
        4275,
    ],
    "setpoints": [
        4149,
        4150,
        4151,
        4148,
    ],
    "eeprom_settings": [
        4154,
        4162,
        4163,
    ],
    "aux_control": [
        4175,
        4174,
        4226,
        4177,
        4176,
    ],
    "network_config": [
        20481,
        20482,
        20483,
        20486,
        20487,
        20484,
        20485,
        20488,
        20489,
        20490,
        20491,
    ],
    "eeprom_config": [
        4327,
        4332,
        4326,
        4246,
        4247,
        4331,
        4335,
        4296,
        4199,
        4198,
        4294,
        4257,
        4249,
        4265,
        4264,
        4245,
        4244,
        4298,
        4299,
        4318,
        4287,
    ],
    "advanced_status": [
        4123,
        4109,
        4124,
        4136,
        4137,
        4145,
        4236,
        4183,
        4327,
        4354,
        4355,
        4202,
        4214,
        4215,
        4216,
        4217,
        4218,
        4254,
        4256,
        4341,
        4342,
        4343,
        4344,
        4297,
        4105,
        4135,
        4276,
        4224,
        4221,
        4238,
        4239,
        4200,
        4197,
        4284,
        4356,
        4295,
        4191,
        4283,
    ],
    "advanced_config": [
        4164,
        4165,
        4180,
        4182,
        4186,
        4187,
        4207,
        4146,
    ],
    "voltage_offsets": [
        4189,
        4190,
        4191,
        4192,
    ],
    "temp_comp": [
        4155,
        4156,
        4157,
    ],
}

# Charge stage mappings (from register 4120 MSB)
CHARGE_STAGES = {
    0: "Resting",
    3: "Absorb",
    4: "BulkMPPT",
    5: "Float",
    6: "FloatMppt",
    7: "Equalize",
    10: "HyperVoc",
    18: "EqMppt",
}

# Internal state mappings (from register 4120 LSB)
INTERNAL_STATES = {
    0: "Resting",
    1: "Waking/Starting (state 1)",
    2: "Waking/Starting (state 2)",
    3: "MPPT / Regulating Voltage (state 3)",
    4: "MPPT / Regulating Voltage (state 4)",
    6: "MPPT / Regulating Voltage (state 6)",
}

# Device types from register 4101
DEVICE_TYPES = {
    150: "Classic 150",
    200: "Classic 200",
    250: "Classic 250",
    251: "Classic 250 KS (120V battery capability)",
}

# Rest reasons from register 4275
REST_REASONS = {
    1: "Anti-Click. Not enough power available (Wake Up)",
    2: "Insane Ibatt Measurement (Wake Up)",
    3: "Negative Current (load on PV input?) (Wake Up)",
    4: "PV Input Voltage lower than Battery V (Vreg state)",
    5: "Too low of power out and Vbatt below set point for > 90 seconds",
    6: "FET temperature too high (Cover is on maybe?)",
    7: "Ground Fault Detected",
    8: "Arc Fault Detected",
    9: "Too much negative current while operating (backfeed from battery out of PV input)",
    10: "Battery is less than 8.0 Volts",
    11: "PV input is available but V is rising too slowly. Low Light or bad connection (Solar mode)",
    12: "Voc has gone down from last Voc or low light. Re-check (Solar mode)",
    13: "Voc has gone up from last Voc enough to be suspicious. Re-check (Solar mode)",
    14: "Same as 11",
    15: "Same as 12",
    16: "MPPT MODE is OFF (Usually because user turned it off)",
    17: "PV input is higher than operation range (too high for 150V Classic)",
    18: "PV input is higher than operation range (too high for 200V Classic)",
    19: "PV input is higher than operation range (too high for 250V or 250KS)",
    22: "Average Battery Voltage is too high above set point",
    25: "Battery Voltage too high of Overshoot (small battery or bad cable?)",
    26: "Mode changed while running OR Vabsorb raised more than 10.0 Volts at once OR Nominal Vbatt changed by modbus command AND MpptMode was ON when changed",
    27: "Bridge center == 1023 (R132 might have been stuffed) This turns MPPT Mode to OFF",
    28: "NOT Resting but RELAY is not engaged for some reason",
    29: "ON/OFF stays off because WIND GRAPH is illegal (current step is set for > 100 amps)",
    30: "PkAmpsOverLimit... Software detected too high of PEAK output current",
    31: "AD1CH.IbattMinus > 900 Peak negative battery current > 90.0 amps (Classic 250)",
    32: "Aux 2 input commanded Classic off for HI or LO (Aux2Function == 15 or 16)",
    33: "OCP in a mode other than Solar or PV-Uset",
    34: "AD1CH.IbattMinus > 900 Peak negative battery current > 90.0 amps (Classic 150, 200)",
    35: "Battery voltage is less than Low Battery Disconnect (LBD) Typically Vbatt is less than 8.5 volts",
}

# Force flag bit mappings (from register 4160)
FORCE_FLAGS = {
    "ForceEEpromUpdate": 2,      # Bit position
    "ForceEEpromInitRead": 3,
    "ForceResetInfoFlags": 4,
    "ForceFloat": 5,
    "ForceBulk": 6,
    "ForceEqualize": 7,
    "ForceNite": 8,
    "ResetAeqCounts": 13,
    "ForceSweep": 16,
    "ResetFlags": 20,             # Bit position
    "ForceResetFaults": 29,
}
